version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
